// Tests for the Denkstand write-seam (plugins/pts-denkstand-writer/lib/index.js)
// and its live integration into the pts:denkstand context.

import test from 'node:test';
import assert from 'node:assert/strict';

import { runOperation, renamedMomentTitles } from '../plugins/pts-denkstand-writer/lib/index.js';
import { STATUS, SIGNIFICANCE, emptyState, record as recordEntry, hypothesize, projectCurrentState } from '../dsh/presets/pts-companion/denkstand-state.mjs';
import { renderDenkstandContext } from '../dsh/presets/pts-companion/pts-context.mjs';

test('record + confirm move an entry to confirmed teacher ground', () => {
	let out = runOperation(emptyState(), { operation: 'record', status: 'teacher_open', statement: 'Gott als Gegenüber', id: 'e1' });
	assert.equal(out.ok, true);
	assert.equal(out.result.entry.status, STATUS.OPEN);
	out = runOperation(out.state, { operation: 'confirm', id: 'e1' });
	assert.equal(out.ok, true);
	assert.equal(out.result.entry.status, STATUS.CONFIRMED);
	assert.equal(out.result.entry.confirmedBy, 'teacher');
});

test('hypothesize lands as assistant hypothesis; only confirm promotes it', () => {
	let out = runOperation(emptyState(), { operation: 'hypothesize', statement: 'Vielleicht Nähe', id: 'h1' });
	assert.equal(out.result.entry.status, STATUS.HYPOTHESIS);
	out = runOperation(out.state, { operation: 'confirm', id: 'h1' });
	assert.equal(out.result.entry.status, STATUS.CONFIRMED);
});

test('reject removes from active state; supersede replaces an older reading', () => {
	let out = runOperation(emptyState(), { operation: 'hypothesize', statement: 'Gott als Freund', id: 'h1' });
	out = runOperation(out.state, { operation: 'supersede', oldId: 'h1', status: 'teacher_confirmed', statement: 'Gott als Gegenüber', id: 'e2' });
	assert.equal(out.ok, true);
	assert.equal(out.result.superseded, 'h1');
	const view = projectCurrentState(out.state);
	assert.equal(view[STATUS.HYPOTHESIS].length, 0);
	assert.equal(view[STATUS.CONFIRMED][0].statement, 'Gott als Gegenüber');
	assert.equal(view[STATUS.REJECTED][0].id, 'h1');
});

test('renaming a moment via supersede threads its former title to the board reconcile', () => {
	// A moment rename is a supersede: the old moment entry is rejected and a new
	// one (new id, new title) is recorded. The writer maps the NEW id to the old
	// title so the board relabels the moment page in place instead of orphaning it.
	let state = emptyState();
	state = recordEntry(state, { status: STATUS.CONFIRMED, statement: 'Gott als Freund', author: 'teacher', id: 'lm-old', kind: 'moment', significance: SIGNIFICANCE.ANCHOR }).state;
	const out = runOperation(state, { operation: 'supersede', oldId: 'lm-old', status: 'teacher_confirmed', statement: 'Gott als Gegenüber', kind: 'moment', id: 'lm-new' });
	assert.equal(out.ok, true);
	const previousTitles = renamedMomentTitles(state, { operation: 'supersede', oldId: 'lm-old', kind: 'moment' }, out);
	// The new entry id is generated by supersede; the map keys it to the old title.
	assert.deepEqual(previousTitles, { [out.result.entry.id]: 'Gott als Freund' });
	assert.notEqual(out.result.entry.id, 'lm-old');
});

test('only a moment rename threads a previous title (non-moment and non-supersede stay empty)', () => {
	let state = emptyState();
	state = recordEntry(state, { status: STATUS.CONFIRMED, statement: 'Eine Entscheidung', author: 'teacher', id: 'd-old', kind: 'decision' }).state;
	const superseded = runOperation(state, { operation: 'supersede', oldId: 'd-old', status: 'teacher_confirmed', statement: 'Andere Entscheidung', kind: 'decision', id: 'd-new' });
	assert.deepEqual(renamedMomentTitles(state, { operation: 'supersede', oldId: 'd-old' }, superseded), {});
	const recorded = runOperation(emptyState(), { operation: 'record', status: 'teacher_confirmed', statement: 'X', id: 'x', kind: 'moment' });
	assert.deepEqual(renamedMomentTitles(emptyState(), { operation: 'record' }, recorded), {});
});

test('a fact requires a source and unknown operations fail cleanly', () => {
	const noSource = runOperation(emptyState(), { operation: 'record', status: 'facts', statement: 'x' });
	assert.equal(noSource.ok, false);
	assert.equal(noSource.error.code, 'fact-requires-source');
	const unknown = runOperation(emptyState(), { operation: 'frobnicate' });
	assert.equal(unknown.ok, false);
	assert.equal(unknown.error.code, 'unknown-operation');
});

test('current reads the state without mutating it', () => {
	const state = runOperation(emptyState(), { operation: 'record', status: 'teacher_confirmed', statement: 'C', id: 'c' }).state;
	const out = runOperation(state, { operation: 'current' });
	assert.equal(out.ok, true);
	assert.equal(out.state, state); // unchanged reference → no write
	assert.equal(out.result.current[STATUS.CONFIRMED][0].statement, 'C');
});

test('the current state is projected into the live pts:denkstand context', () => {
	let state = emptyState();
	state = recordEntry(state, { status: STATUS.CONFIRMED, statement: 'Gott als Gegenüber', author: 'teacher', id: 'c', significance: SIGNIFICANCE.ANCHOR }).state;
	state = hypothesize(state, { statement: 'Vielleicht Nähe', id: 'h' }).state;
	const text = renderDenkstandContext({
		cwd: 'F:/dsh-instances/pts/denkraeume/x',
		repoRoot: 'F:/code/pedagogical-thinking-space/',
		presentFiles: ['learning-design.md'],
		currentState: state,
	});
	assert.match(text, /CURRENT DENKSTAND/);
	assert.match(text, /Bestätigt \(Lehrkraft\):[\s\S]*Gott als Gegenüber/);
	assert.match(text, /Companion-Hypothesen/);
	// Without a current state the context is unchanged (no CURRENT DENKSTAND block).
	const plain = renderDenkstandContext({ cwd: 'x', presentFiles: [] });
	assert.doesNotMatch(plain, /CURRENT DENKSTAND/);
});
